version: "3"

services:
  focus-backend-db:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: db
    ports:
      - "5433:5432"

  backend:
    image: thefocuscompany/backend-go
    build:
      context: .
    container_name: focus-backend
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      DB_ADDR: db:5432
